# https://fly.io/docs/reference/configuration

app = "dagger-registry-2023-01-23"
kill_signal = "SIGINT"
# Wait these many seconds for existing connections to drain before hard killing
kill_timeout = 30
processes = []

# There is no build config since this will always be deployed with a specific
# --image flag. This is currently a pipeline concern. FTW, the app image has
# the build run embedded in /BUILD_URL file.
# [build]

[env]
  PORT = "8080"

[deploy]
  strategy = "bluegreen"

[experimental]
  auto_rollback = true
  cmd = ["-repo", "dagger"]

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 800
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "5s"
    restart_limit = 0
    timeout = "4s"
