name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dagger
        shell: bash
        run: |
          echo "::group::Installing dagger"
          curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin/ sudo -E sh
          echo "::endgroup::"

      - name: Checks
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        run: |
          dagger --cloud checks

      - name: Publish
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        run: |
          dagger --cloud call publish \
            --fly-token env:FLY_API_TOKEN \
            --git-sha "$GITHUB_SHA" \
            --git-author "$GITHUB_ACTOR" \
            --build-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
